module.exports = CONSTANTS = {
    COLORS: {
        WHITE: '#FFFFFF',
        GRAY: '#CCCCCC',
        BLACK: '#000000',
        TRANSPERANT: "rgba(52, 52, 52, 0)",
        SHADOWCOLOR: 'rgba(0, 0, 0, 0.16)',
        PRIMARY: '#1E3072',
        PRIMARY2: '#6B9E3F',
        PRIMARY3: '#174B97',//174b97
        YELLOW: '#FFC000',
        YELLOWPURE: 'yellow',
        PINK: '#FF66FF',
        GRAY2: '#eee',
        TEXTCOLOR2: '#1155cc',
        TEXTCOLOR3: '#FF93B1',
        RED: '#ff0000',
        BLACK2: '#777',
        TABACTIVECOLOR: '#063579',
        TABCOLOR: '#6b9e3f',
        BORDERCOLOR: '#f5f5f5',
        TEXTCOLOR4: '#666666',
        TEXTCOLOR10: '#888888',
        HEADINGCOLOR: '#950008',
        OVERLAYBACKGROUND: 'rgba(0,0,0,.4)',
        DROPDOWN: '#5C5C5C',
        ERROR: '#ffff00',
        BLUE: 'blue',
        ORANGE: '#FC9',
        LIGHTGREEN: '#E8FED5',
    },
    FONT_SIZES: {
        NORMAL: 15,
        HEADING: 18,
        SMALL: 14,
        EXTRASMALL: 12,
        LARGE: 20,
        ABOVELARGE: 30,
        LARGER: 40,
        FONT15: 15,
        FONT20: 20,
        FONT23: 23,
        FONT25: 25,
        MICROSMALL: 10,
        FONT36: 36,
    },
    FONT_FAMILIES: {
        ARIAL: 'Arial',
        AVENIRHEAVY: 'Avenir-Heavy',
    },
    GEOLOCATION_OPTIONS: {
        enableHighAccuracy: true, 
        timeout: 20000, 
        maximumAge: 1000,
    },
    API_KEYS: {
        TOKEN: 'WEFG3RT3745T734TD34TR3DR347R3S8RE',
        SUCCESS: 'success',
        FAILURE: 'failure'
    },
    INPUT_TYPES: {
        TEXT: 'text',
        EMAIL: 'email',
        PASSWORD: 'password',
        FILE: 'file',
        MOBILE: 'mobile',
    },
    SESSIONKEYS: {
        USERINFORMATION: 'userInformation',
        FCM: 'fcmToken',
        REMEMBERUSER: 'loginInformation',
        SESSIONKEY: 'sessionKey',
        FROMNOTIFICATION: 'fromNotification',
    },
    ENVIRONMENTTYPES: {
        PRODUCTION: 'Production',
        TESTING: 'Testing',
        DEVLOPMENT: 'Development',
    },
    REQUESTMETHODS: {
        POST: 'POST',
        GET: 'GET',
    },
    COMPRESS_IMAGE: {
        WIDTH: 500,
        HEIGHT: 500,
        COMPRESSFORMAT: 'JPEG',
        QUALITY: 90,
    },
    ROUTENAMES: {
        Splash: 'Splash',
        Login: 'Login',
        Forgotpassword: 'Forgotpassword',
        App: 'App',
        All: 'All',
        InProgress: 'InProgress',
        Completed: 'Completed',
        ActionRequired: 'ActionRequired',
        Delay: 'Delay',
        CompletedAwaitingPayout: 'CompletedAwaitingPayout',
        Paid: 'Paid',
        ViewOrder: 'ViewOrder',
        Inspection: 'Inspection',
        Instructions: 'Instructions',
        Photos: 'Photos',
        SurveyQuestions: 'SurveyQuestions',
        Sorting: 'Sorting',
    }, 
    CLIENT_ID: {
        bhgClientId: '163',
        fundexClientId: '166',
        hiltonClientId: '144',
    }
}